//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diceware.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diceware.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11111	a
        ///11112	a&apos;s
        ///11113	a-1
        ///11114	a-z
        ///11115	aa
        ///11116	aaa
        ///11121	aaaa
        ///11122	aaron
        ///11123	ab
        ///11124	aback
        ///11125	abacus
        ///11126	abase
        ///11131	abash
        ///11132	abate
        ///11133	abbey
        ///11134	abbot
        ///11135	abbr
        ///11136	abby
        ///11141	abc
        ///11142	abc&apos;s
        ///11143	abcd
        ///11144	abduct
        ///11145	abdul
        ///11146	abe
        ///11151	abed
        ///11152	abel
        ///11153	abet
        ///11154	abhor
        ///11155	abide
        ///11156	ablaze
        ///11161	able
        ///11162	abm
        ///11163	abner
        ///11164	aboard
        ///11165	abode
        ///11166	abort
        ///11211	about
        ///11212	above
        ///11213	abram
        ///11214	absent
        ///11215	absorb
        ///11216	abuse
        ///11221	abut
        ///11222	abyss
        ///11223	ac
        ///11 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BealeWordList {
            get {
                return ResourceManager.GetString("BealeWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11111	a
        ///11112	a&amp;p
        ///11113	a&apos;s
        ///11114	aa
        ///11115	aaa
        ///11116	aaaa
        ///11121	aaron
        ///11122	ab
        ///11123	aba
        ///11124	ababa
        ///11125	aback
        ///11126	abase
        ///11131	abash
        ///11132	abate
        ///11133	abbas
        ///11134	abbe
        ///11135	abbey
        ///11136	abbot
        ///11141	abbott
        ///11142	abc
        ///11143	abe
        ///11144	abed
        ///11145	abel
        ///11146	abet
        ///11151	abide
        ///11152	abject
        ///11153	ablaze
        ///11154	able
        ///11155	abner
        ///11156	abo
        ///11161	abode
        ///11162	abort
        ///11163	about
        ///11164	above
        ///11165	abrade
        ///11166	abram
        ///11211	absorb
        ///11212	abuse
        ///11213	abut
        ///11214	abyss
        ///11215	ac
        ///11216	acadia
        ///11221	accra
        ///11222	accrue
        ///11223	ace
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DicewareWordList {
            get {
                return ResourceManager.GetString("DicewareWordList", resourceCulture);
            }
        }
    }
}
